# -*- coding: utf-8 -*-
"""smartcart_cluster.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B2n_t8vOzWDkex-hbIacujokz84MJVI-

1. Mount Google Drive
"""

from google.colab import drive
drive.mount('/content/drive')

"""check the exact folder pth:-"""

import os
os.listdir('/content/drive/MyDrive/Proj')

"""3 . Import the Particulat data"""

import pandas as pd
file_path = '/content/drive/MyDrive/Proj/smartcart_customers.csv'

file_path = 'smartcart_customers.csv'

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/drive/MyDrive/Proj/smartcart_customers.csv')

df.head()

df.shape

"""1. Data Preprocessing

(IN Data Pre-processing (1 St- step (Handling The Missing value:---)
"""

df["Income"] = df["Income"].fillna(df["Income"] .median())

df.head()

df.isnull().sum()

"""# 2. Feature Engenerring:--"""

df.columns

df["Age"]= 2026-df["Year_Birth"]

df.head()

# Customer Joining Date ( This is a Second Faatures I have created:--)
df["Dt_Customer"] = pd.to_datetime(df["Dt_Customer"], dayfirst=True)

reference_date = df["Dt_Customer"].max()

df["Customer_Tenure_Days"] = (reference_date - df["Dt_Customer"]).dt.days

df.head()

# (Total spending):-- This is a (3rd) Fatures basically I have Craeted:--
df["Total_spending"] = df["MntWines"] + df["MntFruits"] + df["MntMeatProducts"] + df["MntFishProducts"] + df["MntSweetProducts"] + df["MntGoldProds"]

df.head()

# (Children):-- This is a (4rd) Fatures basically I have Craeted:--
df["Total_Children"] = df["Kidhome"] + df["Teenhome"]

# (Eduaction):-- This is a (5th) Fatures basically I have Craeted:--
df["Education"].value_counts()

# step:-- (1) Merge categories using replace()
df["Education"] = df["Education"].replace({
    "Basic": "Undergraduate",
    "2n Cycle": "Undergraduate",
    "Graduation": "Graduate",
    "Master": "Postgraduate",
    "PhD": "Postgraduate"
})

# Step- (2) Merge categories using replace()
# df["Education"] = pd.Categorical(
#     df["Education"],
#     categories=["Undergraduate", "Graduate", "Postgraduate"],
#     ordered=True
# )

df["Education"].value_counts()

# Marital Status:--
df["Marital_Status"] .value_counts()

df["Living_With"] = df["Marital_Status"].replace({
    "Married": "Partner",
    "Together": "Partner",
    "Single": " Alone",
    "Divorced ": "Alone",
    "Widow":  "Alone",
    "Absurd": "Alone",
    "YOLO": "Alone"
})

# df["Living_With"] = pd.Categorical(
#     df["Living_With"],
#     categories=[ "Alone", "Partner",],
#     ordered=True
# )

df["Living_With"]. value_counts()

"""Drop Columns"""

df.head()

df.isnull().sum()

df.dropna

df.isnull().sum()

df.dropna

# Drop Columns:---
cols = ["ID", "Year_Birth", "Marital_Status", "Kidhome", "Teenhome", "Dt_Customer"]

spending_cols = [
    "MntWines",
    "MntFruits",
    "MntMeatProducts",
    "MntFishProducts",
    "MntSweetProducts",
    "MntGoldProds"
]

cols_to_drop = cols + spending_cols

df_cleaned = df.drop(columns=cols_to_drop)

df.columns

df_cleaned.columns

df.head()

df_cleaned.head()

df.shape

df_cleaned.shape # But now we have reduced only (15) columns:---

df_cleaned.head()

"""OUTLIER:-"""

import seaborn as sns
import matplotlib.pyplot as plt

cols = ["Income", "Recency", "Age", "Total_spending", "Total_Children"]

# Pairplot for selected features ( Relative plots of some features:---)
sns.pairplot(df_cleaned[cols])

plt.show()

# Remove the Outliers:--

print("Data size with outliers:" , len(df_cleaned))
df_cleaned = df_cleaned[(df_cleaned["Age"] < 90)]
df_cleaned = df_cleaned[(df_cleaned["Income"] < 600_000)]

print("Data size without outliers:", len(df_cleaned))

"""HEATMAP:-"""

corr = df_cleaned.corr(numeric_only = True)

corr

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8, 6))

sns.heatmap(
    corr,
    annot=True,
    annot_kws={"size": 6},
    cmap="coolwarm"
)
plt.show()

df_cleaned.shape

df_cleaned.head()

"""Feature ENCODING:-"""

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

cat_cols = ["Education", "Living_With"]

enc_cols = ohe.fit_transform(df_cleaned[cat_cols])

enc_df = pd.DataFrame(
    enc_cols.toarray(),
    columns=ohe.get_feature_names_out(cat_cols),
    index = df_cleaned.index
)

df_cleaned = df_cleaned.dropna()

enc_df.head()

# so lets concatinate this encoded data frame with our original Datasets:--

df_encoded=pd.concat([df_cleaned.drop(columns=cat_cols), enc_df],axis=1)

df_encoded.head()

df_encoded.shape

"""SCALING OUR DATA:-"""

from sklearn.preprocessing import StandardScaler

x = df_encoded

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_scaled = scaler.fit_transform(x)

"""VISUALIZE:-"""

x_scaled.shape

df_cleaned.head()

# For 2-D Visulaization:--

from sklearn.decomposition import PCA

pca = PCA(n_components = 2)

X_pca = pca.fit_transform(x_scaled)

# plot

plt.scatter(X_pca[:, 0], X_pca[: , 1])

plt.scatter(X_pca[:,0], X_pca[:,1])
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.show()

pca.explained_variance_ratio_

pca = PCA(n_components = 3)

X_pca = pca.fit_transform(x_scaled)

pca.explained_variance_ratio_

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure(figsize=(8,6))

ax = fig.add_subplot(111, projection="3d")

ax.scatter(X_pca[:,0], X_pca[:,1], X_pca[:,2])

ax.set_xlabel("PC1")
ax.set_ylabel("PC2")
ax.set_zlabel("PC3")

plt.show()

pca.explained_variance_ratio_

"""Analyze The K- value:-- 1.st process use with Elbow Method:-"""

from sklearn.cluster import KMeans

# Install kneed if not already installed
!pip install kneed

from kneed import KneeLocator

wcss = []

for k in range(1, 11):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_pca)
    wcss.append(kmeans.inertia_)

from kneed import KneeLocator

knee = KneeLocator(range(1, 11), wcss, curve="convex", direction="decreasing")

optimal_k = knee.elbow

print("best k= ",optimal_k)

# plot
plt.plot(range(1,11), wcss, marker="o")
plt.xlabel("K")
plt.ylabel("WCSS")

# Best optimal (K = 4) From The Elbow Method:--

"""Silhouette Score:--(2nd process)"""

from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

scores = []

for k in range(2, 11):
    kmeans = KMeans(n_clusters=k, random_state=42)
    labels = kmeans.fit_predict(X_pca)
    score = silhouette_score(X_pca, labels)
    scores.append(score)

# plot
plt.plot(range(2,11), scores, marker="o")
plt.xlabel("K")
plt.ylabel("Silhouette Score")
plt.title("Silhouette Score vs Number of Clusters")
plt.show()

# Next Craet Both Plot for Combined The values:--
k_range = range(2, 11)

fig, ax1 = plt.subplots(figsize=(8, 6))

# Plot WCSS
ax1.plot(k_range, wcss[1:], marker="o", color="blue")
ax1.set_xlabel("Number of Clusters (k)")
ax1.set_ylabel("WCSS", color="blue")
ax1.set_title("Elbow Method and Silhouette Score")

# Create second y-axis
ax2 = ax1.twinx()

# Plot Silhouette Score
ax2.plot(k_range, scores[:len(k_range)], marker="x", color="red", linestyle="--")
ax2.set_ylabel("Silhouette Score", color="red")

plt.show()

"""Now i am Going to apply Cluater Algorithm:--"""

# Hmm Sabse Pahle K- Means Ke Sath Work Karte Hii:--
# (K- Means):--
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=4, random_state=42)

labels_kmeans = kmeans.fit_predict(X_pca)

fig = plt.figure(figsize=(8,6))

ax = fig.add_subplot(111, projection="3d")

ax.scatter(X_pca[:,0], X_pca[:,1], X_pca[:,2],
           c=labels_kmeans, cmap="viridis")

ax.set_xlabel("PC1")
ax.set_ylabel("PC2")
ax.set_zlabel("PC3")
ax.set_title("3D PCA Clusters")

plt.show()

# Aglomarative Clustering
from sklearn.cluster import AgglomerativeClustering
import matplotlib.pyplot as plt

# Create Agglomerative clustering model
agg_cls = AgglomerativeClustering(n_clusters=4, linkage="ward")

# Fit model and get labels
labels_agg = agg_cls.fit_predict(X_pca)

# Create 3D plot
fig = plt.figure(figsize=(8,6))

ax = fig.add_subplot(111, projection="3d")

ax.scatter(X_pca[:,0], X_pca[:,1], X_pca[:,2],
           c=labels_agg, cmap="viridis")

ax.set_xlabel("PC1")
ax.set_ylabel("PC2")
ax.set_zlabel("PC3")
ax.set_title("Agglomerative Clustering")

plt.show()

"""Characterization Of clusters :--"""

df_cleaned.drop("labels", axis=1, errors="ignore", inplace=True)
df_cleaned["cluster"] = labels_agg

df_cleaned.head()

pal = ["red", "blue", "yellow", "green"]

sns.countplot(data=df_cleaned, x="cluster", palette=pal, hue="cluster")

print(df_cleaned.columns)

# Income & Spending patterns (Income - Total spending):--

sns.scatterplot(
    x=df_cleaned["Total_spending"],
    y=df_cleaned["Income"],
    hue=df_cleaned["cluster"],
    palette=pal
)

"""Lets Creat a Cluster summary:-"""

x["cluster"] = labels_agg

x.head()

import seaborn as sns
import matplotlib.pyplot as plt

pal = ["red", "blue", "yellow", "green"]

sns.countplot(x=x["cluster"], palette=pal)

plt.title("Customer Clusters Distribution")
plt.show()

# Income & Spending patterns (Income - Total spending):--

sns.scatterplot(
    x=x["Total_spending"],
    y=x["Income"],
    hue=x["cluster"],
    palette=pal
)

# Cluster Summary:--

cluster_summary = x.groupby("cluster").mean()
print(cluster_summary)

